name: Cypress Sitemap Tests for Xsolla

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ubuntu-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec: ['cypress/e2e/xsollaBlogSitemapTest.cy.js', 'cypress/e2e/xsollaFAQSitemapTest.cy.js', 'cypress/e2e/xsollaIndexSitemapTest.cy.js'] # First half of tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests on Ubuntu
        run: npx cypress run --spec ${spec} # Run specific test file

  windows-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        spec: ['cypress/e2e/xsollaNewsroomSitemapTest.cy.js', 'cypress/e2e/xsollaOthersSitemaptest.cy.js', 'cypress/e2e/xsollaPages2SitemapTest.cy.js'] # Second half of tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests on Windows
        run: npx cypress run --spec ${spec} # Run specific test file
