name: Run Cypress Sitemap Tests for Xsolla.com

on:
  push:
    branches:
      - main  # or the branch you want to trigger the tests on
  pull_request:
    branches:
      - main  # or the branch you want to trigger the tests on

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: |
        npm ci  # Install dependencies from package-lock.json

    - name: Install Cypress
      run: npm install cypress --save-dev  # Install Cypress as a dev dependency

    - name: Run Cypress tests
      run: npx cypress run --spec 'cypress/e2e/'  # Runs all tests in the e2e folder
